// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijtmynbdtfdcvzxgmzlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdG15bmJkdGZkY3Z6eGdtemxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODk3NzQsImV4cCI6MjA2NTc2NTc3NH0.Fw3Jv_bb_7JwdiYQH7q0Uvy3nBtVc1fScB3FnRkw_8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);